#!/bin/bash

ok=1
failures=""
count=0

run() {
    filename=$1
    echo "$filename:"
    basename=${filename%.*}
    suffix=${filename#*.}
    out=$filename.out
    case $suffix in
        adb)
            gnatmake $basename
            ./$basename > $out
            rm -f $basename{,.ali,.o}
            ;;
        bas)
            bwbasic $filename | sed '/ \|^$/d' > $out # Need to filter out the copyright header
            ;;
        c)
            gcc -std=c99 $filename -o $basename
            ./$basename > $out
            rm -f $basename
            ;;
        cpp)
            g++ $filename -o $basename
            ./$basename > $out
            rm -f $basename
            ;;
        cs)
            gmcs $filename
            ./$basename.exe > $out
            rm -f $basename.exe
            ;;
        f)
            gfortran $filename -o $basename
            ./$basename > $out
            rm -f $basename
            ;;
        go)
            go build -o $basename $filename
            ./$basename > $out
            rm -f $basename
            ;;
        java)
            javac $filename
            java $basename > $out
            rm -f $basename.class
            ;;
        pas)
            fpc $filename
            ./$basename > $out
            rm -f $basename $basename.o
            ;;
        scala)
            scalac $filename
            scala $basename > $out
            rm -f *.class
            ;;
        *)
            ./$filename > $out
            ;;
    esac
    if ! cmp -s $out expected-output.txt ; then
        ok=0
        failures="$failures $name"
    fi
    rm -f $out
    (( count++ ))
}

if [ $# -gt 0 ] ; then
    for file in "$@" ; do
        run $file
    done
else
    for file in fizzbuzz.* ; do
        run $file
    done
fi

s=''
if [ $count -ne 1 ] ; then
    s=s
fi
echo Tested $count language$s
if [ $ok -eq 1 ] ; then
    echo OK
else
    echo Failures: $failures
fi
